<wsdl:definitions
xmlns:pet="http://intermediacion.redsara.es/scsp/esquemas/V3/peticion"
xmlns:res="http://intermediacion.redsara.es/scsp/esquemas/V3/respuesta"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://pasaxe.xunta.es/SVDPERMEXWS01/"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
name="SVDPERMEXWS01" targetNamespace="http://pasaxe.xunta.es/SVDPERMEXWS01/">
<wsdl:types>
<xsd:schema
xmlns:pet="http://intermediacion.redsara.es/scsp/esquemas/V3/peticion"
xmlns:res="http://intermediacion.redsara.es/scsp/esquemas/V3/respuesta"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://pasaxe.xunta.es/SVDPERMEXWS01/"
xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://pasaxe.xunta.es/SVDPERMEXWS01/">
<xsd:import
namespace="http://intermediacion.redsara.es/scsp/esquemas/V3/peticion"
schemaLocation="peticion.xsd" />
<xsd:import
namespace="http://intermediacion.redsara.es/scsp/esquemas/V3/respuesta"
schemaLocation="respuesta.xsd" />
</xsd:schema>
</wsdl:types>
<wsdl:message name="SolicitarResponse">
<wsdl:part element="res:Respuesta" name="Respuesta"></wsdl:part>
</wsdl:message>
<wsdl:message name="SolicitarRequest">
<wsdl:part element="pet:Peticion" name="Peticion"></wsdl:part>
</wsdl:message>
<wsdl:portType name="SVDPERMEXWS01">
<wsdl:operation name="Solicitar">
<wsdl:input message="tns:SolicitarRequest"></wsdl:input>
<wsdl:output message="tns:SolicitarResponse"></wsdl:output>
</wsdl:operation>
</wsdl:portType>
<wsdl:binding name="SVDPERMEXWS01SOAP" type="tns:SVDPERMEXWS01">
<soap:binding style="document"
transport="http://schemas.xmlsoap.org/soap/http" />
<wsdl:operation name="Solicitar">
<soap:operation soapAction="solicitudServicio" />
<wsdl:input>
<soap:body use="literal" />
</wsdl:input>
<wsdl:output>
<soap:body use="literal" />
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="SVDPERMEXWS01">
<wsdl:port binding="tns:SVDPERMEXWS01SOAP" name="SVDPERMEXWS01SOAP">
<soap:address location="https://pasaxe.xunta.es/SVDPERMEXWS01" />
</wsdl:port>
</wsdl:service>
</wsdl:definitions>